version: '3.8'

services:
  wiezen_app:
    build: .
    container_name: wiezen_score_tracker
    ports:
      - "8080:8080"
    volumes:
      - ./wiezen.db:/app/wiezen.db
    restart: unless-stopped
